//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R3MUS.Devpack.ESI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("R3MUS.Devpack.ESI.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to agents_research.
        /// </summary>
        public static string AgentsResearch {
            get {
                return ResourceManager.GetString("AgentsResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alliance_ids.
        /// </summary>
        public static string AllianceIds {
            get {
                return ResourceManager.GetString("AllianceIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alliances.
        /// </summary>
        public static string Alliances {
            get {
                return ResourceManager.GetString("Alliances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;.
        /// </summary>
        public static string Ampersand {
            get {
                return ResourceManager.GetString("Ampersand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://login.eveonline.com/oauth/{0}.
        /// </summary>
        public static string AuthorisationUrlFormat {
            get {
                return ResourceManager.GetString("AuthorisationUrlFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to authorize.
        /// </summary>
        public static string Authorise {
            get {
                return ResourceManager.GetString("Authorise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization.
        /// </summary>
        public static string Authorization {
            get {
                return ResourceManager.GetString("Authorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login.eveonline.com.
        /// </summary>
        public static string BaseHostName {
            get {
                return ResourceManager.GetString("BaseHostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;language=en-us.
        /// </summary>
        public static string BaseTailExtra {
            get {
                return ResourceManager.GetString("BaseTailExtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://esi.evetech.net/latest.
        /// </summary>
        public static string BaseURI {
            get {
                return ResourceManager.GetString("BaseURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to datasource=tranquility.
        /// </summary>
        public static string BaseURITail {
            get {
                return ResourceManager.GetString("BaseURITail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blueprints.
        /// </summary>
        public static string Blueprints {
            get {
                return ResourceManager.GetString("Blueprints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to character_ids.
        /// </summary>
        public static string CharacterIds {
            get {
                return ResourceManager.GetString("CharacterIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to characters.
        /// </summary>
        public static string Characters {
            get {
                return ResourceManager.GetString("Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to categories=character&amp;search={0}&amp;strict=true.
        /// </summary>
        public static string CharacterSearchCategories {
            get {
                return ResourceManager.GetString("CharacterSearchCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chat_channels.
        /// </summary>
        public static string ChatChannels {
            get {
                return ResourceManager.GetString("ChatChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to client_id={0}.
        /// </summary>
        public static string ClientIdFormat {
            get {
                return ResourceManager.GetString("ClientIdFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clones.
        /// </summary>
        public static string Clones {
            get {
                return ResourceManager.GetString("Clones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        public static string Comma {
            get {
                return ResourceManager.GetString("Comma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to constellations.
        /// </summary>
        public static string Constellations {
            get {
                return ResourceManager.GetString("Constellations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contracts.
        /// </summary>
        public static string Contracts {
            get {
                return ResourceManager.GetString("Contracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to corporation.
        /// </summary>
        public static string Corporation {
            get {
                return ResourceManager.GetString("Corporation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to corporationhistory.
        /// </summary>
        public static string CorporationHistory {
            get {
                return ResourceManager.GetString("CorporationHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to corporation_ids.
        /// </summary>
        public static string CorporationIds {
            get {
                return ResourceManager.GetString("CorporationIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to corporations.
        /// </summary>
        public static string Corporations {
            get {
                return ResourceManager.GetString("Corporations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icons.
        /// </summary>
        public static string Icons {
            get {
                return ResourceManager.GetString("Icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to journal.
        /// </summary>
        public static string Journal {
            get {
                return ResourceManager.GetString("Journal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to killmails.
        /// </summary>
        public static string Killmails {
            get {
                return ResourceManager.GetString("Killmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mail.
        /// </summary>
        public static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to names.
        /// </summary>
        public static string Names {
            get {
                return ResourceManager.GetString("Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        public static string Plus {
            get {
                return ResourceManager.GetString("Plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recent.
        /// </summary>
        public static string Recent {
            get {
                return ResourceManager.GetString("Recent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to redirect_uri={0}.
        /// </summary>
        public static string RedirectURIFormat {
            get {
                return ResourceManager.GetString("RedirectURIFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to regions.
        /// </summary>
        public static string Regions {
            get {
                return ResourceManager.GetString("Regions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to response_type=code.
        /// </summary>
        public static string ResponseTypeModifier {
            get {
                return ResourceManager.GetString("ResponseTypeModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scope={0}.
        /// </summary>
        public static string ScopeFormat {
            get {
                return ResourceManager.GetString("ScopeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to skillqueue.
        /// </summary>
        public static string SkillQueue {
            get {
                return ResourceManager.GetString("SkillQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to skills.
        /// </summary>
        public static string Skills {
            get {
                return ResourceManager.GetString("Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stations.
        /// </summary>
        public static string Stations {
            get {
                return ResourceManager.GetString("Stations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to structures.
        /// </summary>
        public static string Structures {
            get {
                return ResourceManager.GetString("Structures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to systems.
        /// </summary>
        public static string Systems {
            get {
                return ResourceManager.GetString("Systems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to token.
        /// </summary>
        public static string Token {
            get {
                return ResourceManager.GetString("Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transactions.
        /// </summary>
        public static string Transactions {
            get {
                return ResourceManager.GetString("Transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to types.
        /// </summary>
        public static string Types {
            get {
                return ResourceManager.GetString("Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to universe.
        /// </summary>
        public static string Universe {
            get {
                return ResourceManager.GetString("Universe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to verify.
        /// </summary>
        public static string Verify {
            get {
                return ResourceManager.GetString("Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wallet.
        /// </summary>
        public static string Wallet {
            get {
                return ResourceManager.GetString("Wallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wars.
        /// </summary>
        public static string Wars {
            get {
                return ResourceManager.GetString("Wars", resourceCulture);
            }
        }
    }
}
